apiVersion:   batch/v2alpha1
kind:                    CronJob
metadata:
  name:                  hour-min
spec:
  schedule:              "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name:      date
            image:     busybox
            command:
              - "sh"
              - "-c"
              - "date"
          restartPolicy: OnFailure
